"""Realistic data generators for the multi-source ingest simulator.

Task 12-e. Produces realistic Indian e-commerce context data — customer
records, orders, mobile-banking events, call-center webhooks, ATM-switch-log
rows — that the 4 existing source modules' ``normalize()`` functions can
convert to the unified ``OrderIn`` schema (which the existing
``/v1/risk/score`` endpoint accepts).

The 4 source modules (``src/ingest/{ecommerce,mobile,callcenter,atm}.py``)
were built in Day 4 Track M against the Microsoft Fabric fraud-detection
reference architecture. Each source has its own native event schema
(Kafka topic / CSV row / webhook payload / direct REST). This module's
generators produce events in each source's *native* schema so that
calling the corresponding ``normalize()`` function yields a valid
``OrderIn`` dict — verified by the test suite in
``tests/test_simulator.py``.

Indian e-commerce context:
  * Cities + pincodes — first 3 digits of the Indian 6-digit pincode
    encode the sorting district (e.g. 400 = Mumbai, 110 = Delhi). The
    generator uses real city prefixes so the mock data lines up with
    Indian postal geography.
  * Names — common Indian first/last name combinations across regions
    (Sharma, Patel, Reddy, Nair, etc. — north/south/cultural spread).
  * Phones — +91 country code + 10 digits (matches the Indian mobile
    numbering plan, prefix 6/7/8/9).
  * UPI IDs — standard VPA format (name@bankhandle).
  * Amounts — log-normal distribution (median ~₹1,800, tail to ₹50k)
    matches the RBI digital payments analytics report 2023's per-txn
    amount histogram for UPI P2M transactions.
  * Product categories — Indian e-commerce merchant's typical vertical
    mix (Electronics, Fashion, Groceries, Home, Beauty, Books, Sports).

Cross-source correlation:
  ~20% of events share a customer context across sources — e.g. a
  customer places an e-commerce order, then receives a call-center
  confirmation call, then logs into the mobile app to track the order,
  then makes an ATM withdrawal. This correlation is what makes the
  multi-source ingest pattern valuable: a fraudster who places an
  order + immediately withdraws cash from an ATM in a different city
  in the same window is a strong RTO risk signal (the ``stream-processor``
  would catch this via a per-(customer, window) GeoIP anomaly detector).

RTO risk injection:
  ``inject_rto_risk(order)`` mutates an e-commerce order dict to add
  the canonical RTO risk factors:
    * ``payment_method`` → ``COD`` (the customer pays on delivery —
      merchant bears the return-to-origin cost if they refuse)
    * high amount (₹15k–₹45k — the costly-RTO bucket per the user's
      product hypothesis)
    * ``address_quality`` → ``vague`` (incomplete address → delivery
      likely fails → RTO)
    * ``prior_orders`` → 0 (new customer — no history → no trust score)
    * ``prior_returns`` → 0 (matches the new-customer prior — but a
      truly new customer is a weaker signal than "old customer who
      just started returning"; the model treats 0+0 as "unknown")
  ~15% of generated orders should be RTO-injected per the user's spec.

Source distribution weights (default):
  * ecommerce 0.50  — merchant web-checkout peak throughput
  * mobile    0.25  — mobile banking 2/sec peak
  * callcenter 0.15 — call-center flags 1/5sec
  * atm       0.10  — ATM batch (lowest volume, highest amount)
"""
from __future__ import annotations

import random
import string
import time
from typing import Any

# ---------------------------------------------------------------------------
# Indian geographic + demographic context tables.
# ---------------------------------------------------------------------------

# Indian cities + the first 3 digits of their pincode (sorting district
# code). The full 6-digit pincode is generated by appending 3 random
# digits to the prefix. Source: India Post pin-code directory (public).
CITIES: list[tuple[str, str]] = [
    ("Mumbai", "400"), ("Delhi", "110"), ("Bangalore", "560"),
    ("Hyderabad", "500"), ("Chennai", "600"), ("Kolkata", "700"),
    ("Pune", "411"), ("Ahmedabad", "380"), ("Jaipur", "302"),
    ("Surat", "395"), ("Lucknow", "226"), ("Kanpur", "208"),
]

# City → tier mapping (RBI tier classification: tier_1 = metro,
# tier_2 = large non-metro, tier_3 = smaller cities). Used to derive
# the ``city_tier`` field on OrderIn from the customer's city.
_CITY_TIERS: dict[str, str] = {
    "Mumbai": "tier_1", "Delhi": "tier_1", "Bangalore": "tier_1",
    "Hyderabad": "tier_1", "Chennai": "tier_1", "Kolkata": "tier_1",
    "Pune": "tier_2", "Ahmedabad": "tier_2", "Jaipur": "tier_2",
    "Surat": "tier_2", "Lucknow": "tier_2", "Kanpur": "tier_3",
}

# Realistic Indian first + last name combinations — covers the
# major linguistic/cultural regions so the mock customer roster
# isn't dominated by one region's naming convention.
FIRST_NAMES: list[str] = [
    "Rahul", "Priya", "Amit", "Sneha", "Vikram", "Pooja",
    "Rajesh", "Anita", "Suresh", "Kavya", "Arjun", "Divya",
    "Karan", "Meera", "Sanjay", "Riya", "Nikhil", "Ananya",
    "Aditya", "Isha", "Rohan", "Neha",
]
LAST_NAMES: list[str] = [
    "Sharma", "Patel", "Kumar", "Singh", "Gupta", "Reddy",
    "Nair", "Joshi", "Mehta", "Rao", "Das", "Verma", "Iyer",
    "Kapoor", "Khanna", "Bose",
]

# Product categories an Indian horizontal e-commerce merchant stocks.
PRODUCT_CATEGORIES: list[str] = [
    "Electronics", "Fashion", "Groceries", "Home",
    "Beauty", "Books", "Sports",
]

# Payment modes. Note: OrderIn's payment_method pattern is
# ``^(COD|Prepaid)$`` (only 2 modes accepted by the schema). UPI is
# treated as Prepaid for the e-commerce channel (UPI payment settles
# immediately → no RTO risk). COD is the canonical RTO risk signal.
PAYMENT_MODES: list[str] = ["COD", "Prepaid", "UPI"]

# Mobile-banking merchant categories (RBI MCC codes mapped to short
# strings the OrderIn schema accepts). Mirrors src/ingest/mobile.py.
MOBILE_CATEGORIES: list[str] = [
    "Utilities", "Telecom", "Retail", "Food", "Travel",
    "Recharge", "DTH", "Insurance", "Mutual Fund", "Loan EMI",
]

# Call-center "flag" reason codes — the agent's CRM dropdown selection.
# Mapped to the OrderIn ``category`` field by callcenter.normalize().
CALL_REASONS: list[str] = [
    "customer_dispute", "address_mismatch", "payment_failure",
    "delivery_refused", "fraud_suspicion", "duplicate_order",
]

# ATM card networks present in the Indian market.
CARD_NETWORKS: list[str] = ["VISA", "Mastercard", "RuPay"]

# ATM cash withdrawal denominations (per RBI ATM statistics — typical
# ATM withdrawal amounts cluster around these round numbers).
ATM_AMOUNTS: list[int] = [500, 1000, 2000, 3000, 5000, 10000]

# Realistic Indian UPI VPA handles (the bank/PSP suffix on a UPI ID).
UPI_HANDLES: list[str] = [
    "oksbi", "ybl", "ibl", "axl", "hdfcbank", "pnb", "okicici",
    "paytm", "apl", "oksbi", "ybl",  # weights: SBI + PhonePe dominate
]

# Mobile-app event types — the screen-flow stages a customer traverses.
MOBILE_EVENT_TYPES: list[str] = [
    "app_open", "product_view", "add_to_cart", "checkout", "payment",
]

# Call outcomes — the agent's disposition at call end.
CALL_OUTCOMES: list[str] = ["confirmed", "declined", "unreachable", "voicemail"]

# Default source weights — ecommerce dominates, atm is rarest.
DEFAULT_SOURCE_WEIGHTS: dict[str, float] = {
    "ecommerce": 0.50,
    "mobile": 0.25,
    "callcenter": 0.15,
    "atm": 0.10,
}

# Default per-source event rates (events per second). Source: user's
# product hypothesis (ecommerce peak 5/sec, mobile 2/sec, callcenter
# 1/sec, atm 0.5/sec — atm is daily batch, here it's just slowed).
DEFAULT_RATES_PER_SOURCE: dict[str, float] = {
    "ecommerce": 5.0,
    "mobile": 2.0,
    "callcenter": 1.0,
    "atm": 0.5,
}

# Source → Redis Stream name. New streams specific to the multi-source
# ingest simulator (separate from the existing STREAM_RISK_SCORES which
# carries post-decision audit records, not raw ingest events).
STREAM_INGEST_ECOMMERCE = "ingest.ecommerce"
STREAM_INGEST_MOBILE = "ingest.mobile"
STREAM_INGEST_CALLCENTER = "ingest.callcenter"
STREAM_INGEST_ATM = "ingest.atm"

SOURCE_TO_STREAM: dict[str, str] = {
    "ecommerce": STREAM_INGEST_ECOMMERCE,
    "mobile": STREAM_INGEST_MOBILE,
    "callcenter": STREAM_INGEST_CALLCENTER,
    "atm": STREAM_INGEST_ATM,
}


# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------

def _random_digits(n: int) -> str:
    """Return a string of n random digits (0-9)."""
    return "".join(random.choices(string.digits, k=n))


def _city_to_tier(city: str) -> str:
    """Map a city name to its RBI tier (tier_1/2/3). Defaults to tier_2
    for unknown cities (a conservative default — tier_2 is the
    "neutral" tier in the OrderIn schema's cost-optimizer prior).
    """
    return _CITY_TIERS.get(city, "tier_2")


def _clamp_amount(amount: float, lo: float = 299.0, hi: float = 52_000.0) -> float:
    """Clamp an amount to the OrderIn schema's (1, 1_000_000] bound +
    the realistic ₹299-₹52k e-commerce bucket. ₹299 is the threshold
    below which Indian e-commerce merchants usually don't ship COD
    (shipping cost > margin). ₹52k is the 99th-percentile order amount
    per the user's product hypothesis."""
    return round(max(lo, min(amount, hi)), 2)


# ---------------------------------------------------------------------------
# Customer + per-source event generators.
# ---------------------------------------------------------------------------

def generate_customer(seed: int | None = None) -> dict:
    """Generate a realistic Indian customer record.

    Returns a dict with the customer's name, phone, email, city, pincode,
    address, customer_id, and a city_tier (derived from city). This dict
    is shared context used by all 4 source-specific generators below so
    that correlated cross-source events share a customer.

    Args:
        seed: Optional int seed for reproducibility. When None (the
            default) uses the global ``random`` state — call
            ``random.seed(n)`` before this function for reproducibility
            across all 4 generators in a correlated batch. When set,
            ALL random draws in this function (including the pincode
            + phone digit generation) use a fresh ``random.Random(seed)``
            instance — so two calls with the same seed return the
            same customer.

    Returns:
        A customer-context dict. Not itself a valid OrderIn — the
        per-source generators below pull from this context to build
        source-specific event dicts that the source's ``normalize()``
        converts to OrderIn.
    """
    rng = random.Random(seed) if seed is not None else random
    city, pin_prefix = rng.choice(CITIES)
    # Inline the digit generation so it uses ``rng`` (NOT the global
    # random state) — otherwise seeding this function is futile.
    pincode = pin_prefix + "".join(rng.choices(string.digits, k=3))
    first = rng.choice(FIRST_NAMES)
    last = rng.choice(LAST_NAMES)
    name = f"{first} {last}"
    # Indian mobile numbers start with 6/7/8/9 — the prefix is the
    # carrier-distinguishing digit (TRAI numbering plan 2009).
    phone = "+91" + rng.choice("6789") + "".join(rng.choices(string.digits, k=9))
    # UPI VPA — standard format name@handle.
    upi_id = f"{first.lower()}.{last.lower()}@{rng.choice(UPI_HANDLES)}"
    # Customer ID — merchant's internal stable identifier (a salted hash
    # in production; here a plain CUST-NNNNNN for human readability in
    # the simulator's stdout logs).
    customer_id = f"CUST-{rng.randint(100000, 999999)}"
    return {
        "name": name,
        "phone": phone,
        "email": f"{first.lower()}.{last.lower()}{rng.randint(1000, 9999)}"
                 f"@{'gmail.com' if rng.random() > 0.3 else 'yahoo.in'}",
        "city": city,
        "pincode": pincode,
        "address": f"{rng.randint(1, 200)} {city} {pincode}",
        "customer_id": customer_id,
        "upi_id": upi_id,
        "city_tier": _city_to_tier(city),
    }


def generate_ecommerce_order(customer: dict) -> dict:
    """Generate an e-commerce order event in the OrderIn schema directly.

    The e-commerce channel's ``normalize()`` is the identity function
    (the merchant's web checkout already posts OrderIn-conformant JSON),
    so this generator returns a dict whose fields match OrderIn's
    Pydantic model exactly. After generation, the caller can either:

      * POST the dict directly to ``/v1/risk/score`` with the
        ``X-Channel: ecommerce`` header, OR
      * Publish it to the ``ingest.ecommerce`` Redis Stream (the
        stream-processor will eventually drain it).

    Amount distribution: log-normal with median ~₹1,800 + tail to
    ₹52k. This matches the RBI digital payments analytics report 2023's
    UPI P2M per-txn amount histogram (median ₹1,575; p99 ~₹48k).

    Args:
        customer: A customer-context dict from ``generate_customer()``.
            The order is associated with this customer (the
            ``customer_id`` field is pulled from the context).

    Returns:
        A dict conforming to the OrderIn Pydantic model in
        ``src/api/routes.py``.
    """
    rng = random
    # Log-normal: median = exp(mu) = exp(7.5) ≈ ₹1,808. sigma=0.8 gives
    # a heavy right tail (matches the UPI P2M amount distribution).
    amount = _clamp_amount(rng.lognormvariate(7.5, 0.8))
    payment = rng.choices(PAYMENT_MODES, weights=[0.40, 0.35, 0.25])[0]
    if payment == "UPI":
        # UPI is treated as Prepaid in the OrderIn schema (immediate
        # settlement → no COD RTO risk).
        payment = "Prepaid"
    return {
        "order_id": f"EC-ORD-{rng.randint(100000, 999999)}",
        "amount_inr": amount,
        "category": rng.choice(PRODUCT_CATEGORIES),
        "customer_id": customer["customer_id"],
        "address_quality": rng.choices(
            ["complete", "partial", "vague"], weights=[0.70, 0.20, 0.10]
        )[0],
        "city_tier": customer["city_tier"],
        "payment_method": payment,  # COD or Prepaid (UPI folded in)
        "prior_orders": rng.randint(0, 50),
        "prior_returns": rng.randint(0, 5),
        "items": rng.randint(1, 5),
        "order_hour": rng.randint(8, 23),
        "device": rng.choice(["Web", "Android App", "iOS App"]),
        "merchant_id": f"MERCH-{rng.randint(1, 20):03d}",
    }


def generate_mobile_event(customer: dict, order: dict | None = None) -> dict:
    """Generate a mobile-banking event in the mobile source's native schema.

    The mobile source's ``normalize()`` (``src/ingest/mobile.py``)
    expects these fields: ``upi_id``, ``txn_amount``,
    ``merchant_category``, ``customer_hash``, ``device_id``,
    ``payment_method``, ``txn_hour``, ``city_tier``, ``prior_orders``,
    ``prior_returns``. This generator produces exactly that schema so
    that ``mobile.normalize(event)`` returns a valid OrderIn dict.

    Mobile-banking events are always Prepaid (UPI settles immediately),
    so the ``payment_method`` field is hardcoded to "Prepaid" — matches
    the existing test assertion in ``test_ingest.py``.

    Args:
        customer: Customer-context dict from ``generate_customer()``.
        order: Optional e-commerce order dict (for correlated cross-
            source events). When provided, the mobile event's
            ``upi_id`` references the same customer's UPI VPA so the
            stream-processor's correlation detector can join the two.

    Returns:
        A dict in the mobile-banking source's native event schema.
    """
    rng = random
    # Amount: mobile banking per-txn is smaller than e-commerce per-order
    # (bill payments, recharges, P2P transfers — median ~₹800).
    amount = round(max(500.0, min(rng.lognormvariate(6.7, 0.6), 50000.0)), 2)
    return {
        "upi_id": customer.get("upi_id") or f"cust{_random_digits(6)}@{rng.choice(UPI_HANDLES)}",
        "txn_amount": amount,
        "merchant_category": rng.choice(MOBILE_CATEGORIES),
        "customer_hash": customer["customer_id"],  # already a salted hash in prod
        "device_id": rng.choice(["Android App", "iOS App", "Android Web"]),
        "payment_method": "Prepaid",  # mobile banking is always prepaid (UPI)
        "txn_hour": rng.randint(7, 22),  # banking hours (mobile still active late)
        "city_tier": customer["city_tier"],
        "prior_orders": rng.randint(0, 50),
        "prior_returns": rng.randint(0, 5),
        "event_type": rng.choice(MOBILE_EVENT_TYPES),
        "order_id": order["order_id"] if order else None,
        "event_id": f"MOB-{rng.randint(100000, 999999)}",
        "timestamp": time.time(),
    }


def generate_callcenter_event(customer: dict, order: dict | None = None) -> dict:
    """Generate a call-center webhook payload in the callcenter source's
    native schema.

    The callcenter source's ``normalize()`` (``src/ingest/callcenter.py``)
    expects these fields: ``order_id``, ``order_amount``, ``customer_id``,
    ``reason_code``, ``address_quality``, ``city_tier``,
    ``payment_method``, ``prior_orders``, ``prior_returns``, ``items``,
    ``order_hour``, ``device``, ``agent_id``. This generator produces
    exactly that schema so ``callcenter.normalize(event)`` returns a
    valid OrderIn dict.

    The ``reason_code`` becomes the OrderIn ``category`` field (the
    call center channel uses the agent's flag reason as the per-event
    discriminator — Kandula 2021's "Payment_Type as discriminator"
    insight realized via the channel + reason code).

    Args:
        customer: Customer-context dict.
        order: Optional correlated e-commerce order. When provided,
            the call references the same order_id (the agent is calling
            to confirm a specific flagged order).

    Returns:
        A dict in the call-center webhook payload schema.
    """
    rng = random
    # Call-center orders are typically flagged because something is
    # off — so the amount skews higher than e-commerce average.
    amount = round(rng.uniform(2000, 30000), 2)
    if order:
        order_id = order["order_id"]
        # When the call is about a specific order, the payment_method
        # and amount are inherited from that order (the call-center
        # agent doesn't re-key the order — they confirm the existing
        # order's details).
        amount = order.get("amount_inr", amount)
        payment = order.get("payment_method", rng.choice(["COD", "Prepaid"]))
    else:
        order_id = f"CC-FLAG-{rng.randint(100000, 999999)}"
        payment = rng.choice(["COD", "Prepaid"])
    return {
        "order_id": order_id,
        "order_amount": amount,
        "customer_id": customer["customer_id"],
        "reason_code": rng.choice(CALL_REASONS),
        "address_quality": rng.choices(
            ["complete", "partial", "vague"], weights=[0.40, 0.35, 0.25]
        )[0],  # call-center flags skew toward incomplete addresses
        "city_tier": customer["city_tier"],
        "payment_method": payment,
        "prior_orders": rng.randint(1, 20),  # call-center: usually existing customer
        "prior_returns": rng.randint(0, 3),
        "items": rng.randint(1, 5),
        "order_hour": rng.randint(8, 22),
        "device": rng.choice(["Web", "Android App", "iOS App"]),
        "agent_id": f"AGENT-{rng.randint(100, 999)}",
        # Extra call-specific fields (dropped by normalize → OrderIn):
        "call_id": f"CALL-{rng.randint(100000, 999999)}",
        "call_duration_sec": rng.randint(30, 600),
        "call_outcome": rng.choices(
            CALL_OUTCOMES, weights=[0.55, 0.20, 0.15, 0.10]
        )[0],
        "timestamp": time.time(),
    }


def generate_atm_event(customer: dict) -> dict:
    """Generate an ATM-switch-log CSV row dict in the atm source's
    native schema.

    The atm source's ``normalize()`` (``src/ingest/atm.py``) expects
    these fields: ``txn_id``, ``txn_amount``, ``card_pan_hash``,
    ``card_network``, ``atm_id``, ``atm_location``, ``txn_hour``. This
    generator produces exactly that schema so ``atm.normalize(event)``
    returns a valid OrderIn dict.

    ATM events are always Prepaid (debit card settlement is immediate)
    and carry no address info (the ATM IS the address) — both defaults
    are applied by ``atm.normalize()``.

    Args:
        customer: Customer-context dict. The ``customer_id`` is used as
            the basis for the ``card_pan_hash`` field (in production,
            the PAN hash is a salted SHA-256 of the card number — here
            we mock it as PAN-NNNNNN using the customer_id's numeric
            suffix so correlated events from the same customer join
            cleanly).

    Returns:
        A dict in the ATM-switch-log CSV row schema.
    """
    rng = random
    return {
        "txn_id": f"ATM-TXN-{rng.randint(100000, 999999)}",
        "txn_amount": float(rng.choice(ATM_AMOUNTS)),
        "card_pan_hash": f"PAN-{customer['customer_id'].rsplit('-', 1)[-1]}",
        "card_network": rng.choice(CARD_NETWORKS),
        "atm_id": f"ATM-{rng.randint(1, 50):03d}@{customer['city']}",
        "atm_location": customer["city"],
        "txn_hour": rng.randint(0, 23),
        # Extra ATM-specific fields (dropped by normalize → OrderIn):
        "txn_type": rng.choice(["withdrawal", "balance_inquiry", "pin_change"]),
        "card_last4": _random_digits(4),
        "timestamp": time.time(),
    }


# ---------------------------------------------------------------------------
# RTO risk injection.
# ---------------------------------------------------------------------------

def inject_rto_risk(order: dict) -> dict:
    """Inject RTO risk factors into an e-commerce order dict (mutates
    in place AND returns the same dict for chaining).

    The canonical RTO risk factors per the user's product hypothesis:
      * ``payment_method`` → ``COD`` (customer pays on delivery; the
        merchant bears the return-to-origin shipping cost if they refuse)
      * ``amount_inr`` → high-amount bucket (₹15k–₹45k) — the
        costly-RTO band where a refused delivery costs the merchant
        the most in reverse-logistics fees
      * ``address_quality`` → ``vague`` (incomplete address → delivery
        attempt likely fails → RTO)
      * ``prior_orders`` → 0 (new customer → no history → no trust
        score → can't discriminate legitimate first-time from fraudster)

    The 4 risk factors combined push the cost-optimizer's RTO
    probability above the REVIEW threshold (typically ~0.45) and often
    above the REJECT threshold (~0.65) — depends on the trained model
    weights at the merchant_id level.

    This function is idempotent — calling it on an already-RTO-injected
    order just re-randomizes the amount within the same high bucket.
    Safe to call on any e-commerce order dict.

    Args:
        order: An e-commerce order dict from ``generate_ecommerce_order``.

    Returns:
        The same dict (mutated in place) with RTO risk factors injected.
    """
    order["payment_method"] = "COD"
    # High-amount bucket — costly-RTO band per the user's hypothesis.
    order["amount_inr"] = float(random.choice([15000, 25000, 35000, 45000]))
    order["address_quality"] = "vague"  # incomplete address → delivery likely fails
    order["prior_orders"] = 0  # new customer → no history
    # prior_returns stays as generated (a brand-new customer has 0
    # returns, which is consistent with prior_orders=0).
    return order


# ---------------------------------------------------------------------------
# Source selection + correlation helpers.
# ---------------------------------------------------------------------------

def pick_source(
    weights: dict[str, float] | None = None,
    rng: random.Random | None = None,
) -> str:
    """Pick a source name based on per-source weights.

    Args:
        weights: A dict mapping source name → weight. Defaults to
            ``DEFAULT_SOURCE_WEIGHTS`` (ecommerce 0.5, mobile 0.25,
            callcenter 0.15, atm 0.10).
        rng: Optional Random instance for reproducibility.

    Returns:
        One of "ecommerce", "mobile", "callcenter", "atm".
    """
    w = weights or DEFAULT_SOURCE_WEIGHTS
    sources = list(w.keys())
    vals = [w[s] for s in sources]
    r = rng or random
    return r.choices(sources, weights=vals)[0]


def generate_correlated_chain(customer: dict) -> list[dict]:
    """Generate a correlated cross-source chain for one customer.

    Returns a list of (source, event) tuples representing a realistic
    customer journey that spans all 4 sources:

      1. E-commerce order placed on the web checkout.
      2. Mobile-app login + product_view (the customer tracks the order).
      3. Call-center confirmation call (the agent verifies the order).
      4. ATM withdrawal (the customer pulls cash — possibly to pay COD).

    The chain is what the multi-source ingest pattern is valuable for:
    a fraudster who places a COD order + immediately withdraws cash
    from an ATM in a different city is a strong RTO risk signal.

    Each event's dict is in the source's native schema (matches what
    the source's ``normalize()`` expects).

    Args:
        customer: A customer-context dict.

    Returns:
        A list of (source_name, event_dict) tuples.
    """
    order = generate_ecommerce_order(customer)
    return [
        ("ecommerce", order),
        ("mobile", generate_mobile_event(customer, order)),
        ("callcenter", generate_callcenter_event(customer, order)),
        ("atm", generate_atm_event(customer)),
    ]


def normalize_for_source(source: str, event: dict) -> dict:
    """Dispatch to the source module's ``normalize()`` function.

    Convenience wrapper so the simulator's main loop doesn't have to
    import each source module individually. Returns an OrderIn-
    conformant dict by calling the source's ``normalize()`` function.

    Args:
        source: One of "ecommerce", "mobile", "callcenter", "atm".
        event: A dict in the source's native event schema.

    Returns:
        A dict conforming to the OrderIn Pydantic model.
    """
    # Lazy imports — keeps this module import-safe in test envs that
    # don't have all 4 source modules loaded (shouldn't happen, but
    # defensive against partial installs).
    if source == "ecommerce":
        from src.ingest import ecommerce
        return ecommerce.normalize(event)
    elif source == "mobile":
        from src.ingest import mobile
        return mobile.normalize(event)
    elif source == "callcenter":
        from src.ingest import callcenter
        return callcenter.normalize(event)
    elif source == "atm":
        from src.ingest import atm
        return atm.normalize(event)
    else:
        raise ValueError(f"unknown source: {source!r}")


def generate_for_source(
    source: str,
    customer: dict | None = None,
    correlated_order: dict | None = None,
) -> tuple[dict, dict]:
    """Generate one source-specific event + return (event, normalized_orderin).

    Convenience wrapper combining generation + normalization in one
    call. Used by the simulator's main loop.

    Args:
        source: One of "ecommerce", "mobile", "callcenter", "atm".
        customer: Optional pre-built customer context (for correlation).
            If None, a fresh customer is generated (uncorrelated event).
        correlated_order: Optional e-commerce order dict — used by the
            mobile + callcenter generators to tie the event to a
            specific order.

    Returns:
        A 2-tuple ``(event_dict, normalized_orderin_dict)`` where the
        first element is the source-native event (matching what
        ``<source>.normalize()`` expects) and the second is the
        OrderIn-conformant dict (the result of calling normalize on
        the first).
    """
    if customer is None:
        customer = generate_customer()
    if source == "ecommerce":
        event = generate_ecommerce_order(customer)
    elif source == "mobile":
        event = generate_mobile_event(customer, correlated_order)
    elif source == "callcenter":
        event = generate_callcenter_event(customer, correlated_order)
    elif source == "atm":
        event = generate_atm_event(customer)
    else:
        raise ValueError(f"unknown source: {source!r}")
    normalized = normalize_for_source(source, event)
    return event, normalized
