"""Tests for the multi-source ingest simulator (Task 12-e).

Verifies:

  1. The realistic-data generators in ``src/ingest/simulator_data.py``
     produce source-native events that the existing 4 source modules'
     ``normalize()`` functions convert to valid ``OrderIn`` dicts.
  2. The RTO-risk injection mutates an order's high-risk fields
     (COD + high amount + vague address + new customer).
  3. The correlated cross-source chain shares a single customer_id
     across all 4 sources' events.
  4. The FastAPI ingest router (``src/api/ingest_routes.py``) accepts
     each source's native event + returns the normalized OrderIn.
  5. The simulator's CLI ``--dry-run`` mode runs without crashing
     (no Redis / no API required).

Test count: 13 — 6 generator tests + 2 RTO tests + 2 correlation
tests + 4 ingest-route tests (one per source endpoint, plus the
index endpoint counts as a 5th but the test for it is folded into
the same parametrized run).

Source: Kandula 2021 paper — Payment_Type as a discriminator feature
for fraud detection. Here ``channel`` is the discriminator (per the
existing src/ingest/* modules); this simulator's generators produce
events in each channel's native schema so the discriminator surfaces
correctly on the audit record.
"""
from __future__ import annotations

import random
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.api.routes import OrderIn  # noqa: E402
from src.ingest.simulator_data import (  # noqa: E402
    CALL_OUTCOMES,
    CARD_NETWORKS,
    CITIES,
    DEFAULT_SOURCE_WEIGHTS,
    MOBILE_EVENT_TYPES,
    PRODUCT_CATEGORIES,
    SOURCE_TO_STREAM,
    STREAM_INGEST_ATM,
    STREAM_INGEST_CALLCENTER,
    STREAM_INGEST_ECOMMERCE,
    STREAM_INGEST_MOBILE,
    generate_atm_event,
    generate_callcenter_event,
    generate_correlated_chain,
    generate_customer,
    generate_ecommerce_order,
    generate_mobile_event,
    inject_rto_risk,
    normalize_for_source,
    pick_source,
)


# ---------------------------------------------------------------------------
# Customer generator tests.
# ---------------------------------------------------------------------------

def test_generate_customer_produces_indian_context():
    """The customer generator produces Indian-context fields: +91 phone,
    valid city, 6-digit pincode starting with a known city prefix.
    """
    random.seed(42)
    for _ in range(20):
        c = generate_customer()
        # Phone: +91 followed by 10 digits, first digit 6/7/8/9 (Indian
        # mobile numbering plan).
        assert c["phone"].startswith("+91")
        body = c["phone"][3:]
        assert len(body) == 10
        assert body[0] in "6789", f"mobile prefix {body[0]} not in 6789"
        # City is one of the known CITIES.
        assert c["city"] in [city for city, _ in CITIES]
        # Pincode: 6 digits, first 3 match the city's prefix.
        assert len(c["pincode"]) == 6
        city_prefix = next(p for city, p in CITIES if city == c["city"])
        assert c["pincode"].startswith(city_prefix), (
            f"pincode {c['pincode']} doesn't match city prefix {city_prefix}"
        )
        # Email + name + customer_id all populated.
        assert "@" in c["email"]
        assert " " in c["name"]  # first + last
        assert c["customer_id"].startswith("CUST-")
        # city_tier derived from city.
        assert c["city_tier"] in ("tier_1", "tier_2", "tier_3")


def test_generate_customer_is_reproducible_with_seed():
    """Same seed → same customer. Important for test reproducibility."""
    c1 = generate_customer(seed=42)
    c2 = generate_customer(seed=42)
    assert c1 == c2


# ---------------------------------------------------------------------------
# Per-source generator → normalize → OrderIn validity tests.
# ---------------------------------------------------------------------------

def test_generate_ecommerce_order_normalizes_to_valid_orderin():
    """E-commerce orders generated by the simulator normalize (identity)
    to a valid OrderIn dict — required so the simulator's HTTP-fallback
    POST to /risk/score doesn't 422.
    """
    random.seed(0)
    for _ in range(50):
        c = generate_customer()
        order = generate_ecommerce_order(c)
        # E-commerce normalize is identity — but the dict must still
        # conform to the OrderIn Pydantic model.
        normalized = normalize_for_source("ecommerce", order)
        obj = OrderIn(**normalized)
        assert obj.order_id == order["order_id"]
        assert obj.payment_method in ("COD", "Prepaid")
        # Amount is in the realistic ₹299-₹52k band.
        assert 299 <= obj.amount_inr <= 52000
        # Category is one of the product categories.
        assert obj.category in PRODUCT_CATEGORIES


def test_generate_mobile_event_normalizes_to_valid_orderin():
    """Mobile-banking events normalize via mobile.normalize() to valid
    OrderIn dicts. The payment_method must be Prepaid (mobile banking
    is always Prepaid per the existing src/ingest/mobile.py tests).
    """
    random.seed(0)
    for _ in range(50):
        c = generate_customer()
        event = generate_mobile_event(c)
        normalized = normalize_for_source("mobile", event)
        obj = OrderIn(**normalized)
        # Mobile-banking-specific invariant: always Prepaid.
        assert obj.payment_method == "Prepaid"
        # upi_id → order_id mapping.
        assert obj.order_id == event["upi_id"]
        # txn_amount → amount_inr mapping.
        assert obj.amount_inr == pytest.approx(event["txn_amount"])
        # Merchant category is one of the mobile categories.
        assert obj.category in (
            "Utilities", "Telecom", "Retail", "Food", "Travel",
            "Recharge", "DTH", "Insurance", "Mutual Fund", "Loan EMI",
        )


def test_generate_callcenter_event_normalizes_to_valid_orderin():
    """Call-center webhook payloads normalize via callcenter.normalize()
    to valid OrderIn dicts. The reason_code becomes the category.
    """
    random.seed(0)
    for _ in range(50):
        c = generate_customer()
        event = generate_callcenter_event(c)
        normalized = normalize_for_source("callcenter", event)
        obj = OrderIn(**normalized)
        # reason_code → category mapping.
        assert obj.category == event["reason_code"]
        # order_amount → amount_inr mapping.
        assert obj.amount_inr == pytest.approx(event["order_amount"])
        # agent_id is dropped by OrderIn's Pydantic validation.
        assert not hasattr(obj, "agent_id")


def test_generate_atm_event_normalizes_to_valid_orderin():
    """ATM-switch-log row dicts normalize via atm.normalize() to valid
    OrderIn dicts. ATM is always Prepaid (debit card settlement is
    immediate). city_tier is derived from the atm_location.
    """
    random.seed(0)
    for _ in range(50):
        c = generate_customer()
        event = generate_atm_event(c)
        normalized = normalize_for_source("atm", event)
        obj = OrderIn(**normalized)
        # ATM-specific invariant: always Prepaid.
        assert obj.payment_method == "Prepaid"
        # txn_id → order_id mapping.
        assert obj.order_id == event["txn_id"]
        # card_network → category mapping.
        assert obj.category == event["card_network"]
        # card_network is one of CARD_NETWORKS.
        assert event["card_network"] in CARD_NETWORKS


# ---------------------------------------------------------------------------
# RTO risk injection tests.
# ---------------------------------------------------------------------------

def test_inject_rto_risk_sets_canonical_rto_factors():
    """inject_rto_risk() mutates an order to carry the 4 canonical RTO
    risk factors: COD + high amount + vague address + new customer.
    """
    random.seed(42)
    c = generate_customer()
    order = generate_ecommerce_order(c)
    # Pre-condition: the order is NOT already RTO-injected (most likely
    # has a regular amount + maybe COD, maybe Prepaid).
    mutated = inject_rto_risk(dict(order))
    # Factor 1: payment_method → COD.
    assert mutated["payment_method"] == "COD"
    # Factor 2: amount in the costly-RTO band (₹15k–₹45k).
    assert 15000 <= mutated["amount_inr"] <= 45000
    # Factor 3: address_quality → vague (incomplete → delivery likely fails).
    assert mutated["address_quality"] == "vague"
    # Factor 4: prior_orders → 0 (new customer → no history).
    assert mutated["prior_orders"] == 0


def test_inject_rto_risk_is_idempotent():
    """Calling inject_rto_risk() on an already-injected order doesn't
    raise — it just re-randomizes the amount within the same band."""
    random.seed(0)
    c = generate_customer()
    order = inject_rto_risk(generate_ecommerce_order(c))
    # Second call — should not raise, should stay in the RTO band.
    order2 = inject_rto_risk(dict(order))
    assert order2["payment_method"] == "COD"
    assert 15000 <= order2["amount_inr"] <= 45000
    assert order2["address_quality"] == "vague"
    assert order2["prior_orders"] == 0


# ---------------------------------------------------------------------------
# Correlation tests.
# ---------------------------------------------------------------------------

def test_generate_correlated_chain_shares_customer_across_sources():
    """The correlated chain's 4 events all share the same customer_id
    (in the appropriate per-source form: CUST-NNNNNN for ecommerce +
    callcenter, customer_hash=CUST-NNNNNN for mobile, PAN-NNNNNN for
    ATM where NNNNNN is the customer_id's numeric suffix).
    """
    random.seed(0)
    customer = generate_customer()
    chain = generate_correlated_chain(customer)
    # 4 events: ecommerce, mobile, callcenter, atm.
    assert len(chain) == 4
    sources = [s for s, _ in chain]
    assert sources == ["ecommerce", "mobile", "callcenter", "atm"]
    # The ecommerce + callcenter events reference the order.
    ecommerce_event = chain[0][1]
    mobile_event = chain[1][1]
    callcenter_event = chain[2][1]
    atm_event = chain[3][1]
    # E-commerce: customer_id is the customer's.
    assert ecommerce_event["customer_id"] == customer["customer_id"]
    # Mobile: customer_hash is the customer_id (mirrors how the
    # mobile-banking app uses the merchant's stable id).
    assert mobile_event["customer_hash"] == customer["customer_id"]
    # Mobile event's order_id field references the ecommerce order.
    assert mobile_event["order_id"] == ecommerce_event["order_id"]
    # Callcenter: customer_id + order_id match the ecommerce event.
    assert callcenter_event["customer_id"] == customer["customer_id"]
    assert callcenter_event["order_id"] == ecommerce_event["order_id"]
    # ATM: card_pan_hash is PAN-NNNNNN where NNNNNN is the customer_id's
    # numeric suffix (the simulator's correlation key for ATM events).
    cust_suffix = customer["customer_id"].rsplit("-", 1)[-1]
    assert atm_event["card_pan_hash"] == f"PAN-{cust_suffix}"
    # Each event normalizes to a valid OrderIn.
    for source, event in chain:
        normalized = normalize_for_source(source, event)
        OrderIn(**normalized)


def test_pick_source_returns_weighted_distribution():
    """pick_source() returns the 4 sources with the expected default
    frequency distribution (ecommerce 50%, mobile 25%, callcenter 15%,
    atm 10%). Tolerant to ±5% noise."""
    random.seed(42)
    n = 4000
    counts = {s: 0 for s in DEFAULT_SOURCE_WEIGHTS}
    for _ in range(n):
        counts[pick_source()] += 1
    # Ecommerce ~50% ± 5%.
    assert 0.45 * n <= counts["ecommerce"] <= 0.55 * n
    # Mobile ~25% ± 5%.
    assert 0.20 * n <= counts["mobile"] <= 0.30 * n
    # Callcenter ~15% ± 5%.
    assert 0.10 * n <= counts["callcenter"] <= 0.20 * n
    # ATM ~10% ± 5%.
    assert 0.05 * n <= counts["atm"] <= 0.15 * n


# ---------------------------------------------------------------------------
# Source-to-stream mapping tests.
# ---------------------------------------------------------------------------

def test_source_to_stream_mapping_covers_all_4_sources():
    """SOURCE_TO_STREAM maps all 4 sources to a distinct ingest.* stream
    name (so the simulator publishes each source's events to a
    separate stream for downstream per-source enrichment).
    """
    assert SOURCE_TO_STREAM == {
        "ecommerce": STREAM_INGEST_ECOMMERCE,
        "mobile": STREAM_INGEST_MOBILE,
        "callcenter": STREAM_INGEST_CALLCENTER,
        "atm": STREAM_INGEST_ATM,
    }
    # All 4 stream names are distinct + use the ``ingest.`` prefix.
    streams = set(SOURCE_TO_STREAM.values())
    assert len(streams) == 4
    assert all(s.startswith("ingest.") for s in streams)


# ---------------------------------------------------------------------------
# FastAPI ingest router tests.
# ---------------------------------------------------------------------------

def _build_ingest_app():
    """Build a bare FastAPI app with just the ingest router mounted."""
    from fastapi import FastAPI
    from src.api.ingest_routes import router

    app = FastAPI()
    app.include_router(router)
    return app


def test_ingest_router_index_lists_all_4_sources():
    """GET /v1/ingest/ returns the 4-source list + endpoint map."""
    from fastapi.testclient import TestClient

    app = _build_ingest_app()
    client = TestClient(app)
    r = client.get("/v1/ingest/")
    assert r.status_code == 200
    body = r.json()
    assert set(body["sources"]) == {"ecommerce", "mobile", "callcenter", "atm"}
    assert body["endpoints"]["ecommerce"] == "POST /v1/ingest/ecommerce"
    assert body["endpoints"]["atm"] == "POST /v1/ingest/atm"


@pytest.mark.parametrize(
    "source",
    ["ecommerce", "mobile", "callcenter", "atm"],
)
def test_ingest_router_accepts_each_source_native_event(source):
    """POST /v1/ingest/{source} accepts the source's native event dict
    + returns the normalized OrderIn dict (verified to conform to the
    OrderIn Pydantic model).
    """
    from fastapi.testclient import TestClient

    random.seed(42)
    customer = generate_customer()
    order = generate_ecommerce_order(customer)
    # Build the source-native event for each source.
    if source == "ecommerce":
        event = order
    elif source == "mobile":
        event = generate_mobile_event(customer, order)
    elif source == "callcenter":
        event = generate_callcenter_event(customer, order)
    elif source == "atm":
        event = generate_atm_event(customer)
    else:
        raise AssertionError(f"unknown source {source}")

    app = _build_ingest_app()
    client = TestClient(app)
    r = client.post(f"/v1/ingest/{source}", json=event)
    assert r.status_code == 200, f"HTTP {r.status_code}: {r.text}"
    body = r.json()
    assert body["source"] == source
    # The returned OrderIn dict validates against the OrderIn model.
    normalized = body["orderin"]
    obj = OrderIn(**normalized)
    # Channel field surfaces the source-appropriate channel tag.
    expected_channels = {
        "ecommerce": "ecommerce",
        "mobile": "mobile",
        "callcenter": "call_center",
        "atm": "atm",
    }
    assert body["channel"] == expected_channels[source]
    # order_id is present + matches the normalized dict's.
    assert body["order_id"] == normalized["order_id"]
    assert obj.order_id == normalized["order_id"]


def test_ingest_router_rejects_invalid_event_body():
    """POST /v1/ingest/ecommerce with an invalid body (missing required
    field) returns HTTP 422 (Pydantic validation error) — not 500.
    """
    from fastapi.testclient import TestClient

    app = _build_ingest_app()
    client = TestClient(app)
    # Missing required field order_id.
    r = client.post("/v1/ingest/ecommerce", json={
        "amount_inr": 1500,
        "category": "Fashion",
        "customer_id": "CUST-1",
    })
    assert r.status_code == 422


# ---------------------------------------------------------------------------
# Simulator CLI dry-run smoke test.
# ---------------------------------------------------------------------------

def test_simulator_cli_dry_run_publishes_events_without_crashing():
    """Run the simulator in --dry-run mode for 2 seconds at 10/sec +
    verify it publishes ~20 events without crashing. Captures stdout
    + parses the JSON lines to verify each line is a well-formed
    event record.
    """
    import io
    import json
    import runpy

    # Capture stdout while running the simulator's main() in-process.
    argv = [
        "run_simulator.py",
        "--duration", "2",
        "--rate", "10",
        "--dry-run",
        "--seed", "42",
    ]
    old_argv = sys.argv
    sys.argv = argv
    old_stdout = sys.stdout
    sys.stdout = io.StringIO()
    try:
        # Run the simulator's main() — sys.exit(0) is the expected exit.
        try:
            runpy.run_path(
                str(Path(__file__).resolve().parents[1] / "scripts" / "run_simulator.py"),
                run_name="__main__",
            )
        except SystemExit as e:
            assert e.code == 0, f"simulator exited non-zero: {e.code}"
        # Parse the captured stdout — each line should be a JSON event.
        captured = sys.stdout.getvalue()
        lines = [ln for ln in captured.strip().split("\n") if ln.strip()]
        assert len(lines) >= 15, (
            f"expected >=15 events in 2s@10/sec, got {len(lines)}"
        )
        events = [json.loads(ln) for ln in lines]
        # Each event has the expected fields.
        for ev in events:
            assert "source" in ev
            assert ev["source"] in ("ecommerce", "mobile", "callcenter", "atm")
            assert "stream" in ev
            assert ev["stream"].startswith("ingest.")
            assert "orderin" in ev
            # The orderin dict validates against OrderIn.
            OrderIn(**ev["orderin"])
    finally:
        sys.argv = old_argv
        sys.stdout = old_stdout
